### ISSUE TITLE
markdown table columns act strangely on mobile

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/jekyll-theme-cs50#114]
Table here, for example:  https://cs50.harvard.edu/x/2020/faqs
![table](https://user-images.githubusercontent.com/6343970/72021530-18930d00-32d3-11ea-9dc6-a5fa7c323537.png)

First column is made tiny.

**Comment by dmalan** [comment]
Should be fixed!

```css
.markdown-body table {
    word-break: normal;
}
```
