### ISSUE TITLE
Subtitles not Working

### ISSUE THREAD

**Issue by zivmax** [cs50/jekyll-theme-cs50#193]
# Problem

The code:

````markdown
---
title: Step 0 CLI, Linux, WSL
---

# Step 0
## CLI, Linux, WSL

# Title
## Subtitle
````

Renders to a plain result:

![Image](https://github.com/user-attachments/assets/c5ad1a71-9e43-4980-8c1e-d594825fc60a)

# Other Statement
The full code base is [here](https://github.com/shanghaitech-igem/iweb) on GitHub.

Key changes I've made is modify some of the style using sass, but it shouldn't affect contents in the main page or the parsing:
```scss
---
# This is Jekyll front matter
---

// prettier-ignore-start
$vscode-validate: null; // This is for passing the validation of the vscode scss feature.
// prettier-ignore-end

$link-color: #45b06c;
$link-color-dark: #7bcc98;

@import "page";

aside {
  color: #ffffff85;

  h1,
  h2,
  h3 {
    color: #fff;
  }

  ul {
    li {
      overflow-x: hidden;
      overflow-y: hidden;
    }
  }


  p.small {
    color: #fff;
  }
}
```

# Version

Ruby's version:
```
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
```

`Gemfil.lock`'s contents:
```
GIT
  remote: https://github.com/cs50/jekyll-theme-cs50
  revision: 54d238f0e5278e392dd1fc91d61b3bc4759777fd
  branch: develop
  specs:
    jekyll-theme-cs50 (1.1.0)
      deep_merge (= 1.2.2)
      jekyll (= 4.3.4)
      jekyll-algolia (= 1.7.1)
      jekyll-default-layout (= 0.1.5)
      jekyll-optional-front-matter (= 0.3.2)
      jekyll-redirect-from (= 0.16.0)
      jekyll-sass-converter (= 2.2.0)
      jekyll-titles-from-headings (= 0.5.3)
      sanitize (= 6.1.3)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    algolia_html_extractor (2.6.4)
      json (~> 2.0)
      nokogiri (~> 1.10)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    colorator (1.1.0)
    concurrent-ruby (1.3.4)
    crass (1.0.6)
    deep_merge (1.2.2)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.17.0-x86_64-linux-gnu)
    filesize (0.2.0)
    forwardable-extended (2.6.0)
    http_parser.rb (0.8.0)
    httpclient (2.8.3)
    i18n (1.14.6)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.4)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-algolia (1.7.1)
      algolia_html_extractor (~> 2.6)
      algoliasearch (~> 1.26)
      filesize (~> 0.1)
      jekyll (>= 3.6, < 5.0)
      json (~> 2.0)
      nokogiri (~> 1.6)
      progressbar (~> 1.9)
      verbal_expressions (~> 0.1.5)
    jekyll-default-layout (0.1.5)
      jekyll (>= 3.0, < 5.0)
    jekyll-optional-front-matter (0.3.2)
      jekyll (>= 3.0, < 5.0)
    jekyll-redirect-from (0.16.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-sass-converter (2.2.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-titles-from-headings (0.5.3)
      jekyll (>= 3.3, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    json (2.9.0)
    kramdown (2.5.1)
      rexml (>= 3.3.9)
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.4)
    listen (3.9.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    nokogiri (1.17.2-x86_64-linux)
      racc (~> 1.4)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    progressbar (1.13.0)
    public_suffix (6.0.1)
    racc (1.8.1)
    rb-fsevent (0.11.2)
    rb-inotify (0.11.1)
      ffi (~> 1.0)
    rexml (3.4.0)
    rouge (4.5.1)
    safe_yaml (1.0.5)
    sanitize (6.1.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    unicode-display_width (2.6.0)
    verbal_expressions (0.1.5)
    webrick (1.9.1)

PLATFORMS
  x86_64-linux-gnu

DEPENDENCIES
  jekyll-theme-cs50!

BUNDLED WITH
   2.4.20
```
